"""add CalendarDay.date unique=True

Revision ID: ca2aae4b547a
Revises: f01d130b214c
Create Date: 2025-11-16 22:52:37.037739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2aae4b547a'
down_revision = 'f01d130b214c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendarday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarday',
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('is_working_day', sa.BOOLEAN(), nullable=False),
    sa.Column('is_short_day', sa.BOOLEAN(), nullable=False),
    sa.Column('holiday', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
