"""add CalendarDay model

Revision ID: f01d130b214c
Revises: 
Create Date: 2025-11-10 23:03:21.979104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01d130b214c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendarday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendarday',
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('is_working_day', sa.BOOLEAN(), nullable=False),
    sa.Column('is_short_day', sa.BOOLEAN(), nullable=False),
    sa.Column('holiday', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
